# Generated by Django 5.0 on 2025-01-11 09:40

import administration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='business_phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[administration.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[administration.models.validate_phone_number]),
        ),
    ]
