# Generated by Django 5.0 on 2025-11-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0003_alter_customuser_business_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="payment_done",
            field=models.BooleanField(default=False),
        ),
    ]
