# Generated by Django 4.2.16 on 2025-11-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_paymenttransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRequestCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('request_count', models.IntegerField(default=0)),
                ('last_request_time', models.DateTimeField(blank=True, null=True)),
                ('first_request_time', models.DateTimeField(auto_now_add=True)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'OTP Request Counter',
                'verbose_name_plural': 'OTP Request Counters',
                'ordering': ['-last_request_time'],
            },
        ),
    ]
