# Generated by Django 4.2.16 on 2025-11-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_otprequestcounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='admin_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='admin_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('completed', 'Completed'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
