# Generated by Django 4.2.16 on 2025-11-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_paymenttransaction_admin_notified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='subscription_end_date',
            field=models.DateField(blank=True, help_text='Date when subscription expires (1 year from activation)', null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='subscription_start_date',
            field=models.DateField(blank=True, help_text='Date when subscription was activated', null=True),
        ),
    ]
