# Generated by Django 4.2.16 on 2025-11-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_paymenttransaction_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(help_text='e.g., President, Secretary, Treasurer, etc.', max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='committee_members')),
                ('is_active', models.BooleanField(default=True, help_text='Show this member in the active committee')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which to display (lower numbers first)')),
            ],
            options={
                'verbose_name': 'Committee Member',
                'verbose_name_plural': 'Committee Members',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
