"""
Django settings for Saryupari_Brahmin_Project project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
# Python Imports
from pathlib import Path
import os
from dotenv import dotenv_values

# Local Imports
from .constants import ENV_FILE_PATH

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env_vars = dotenv_values(ENV_FILE_PATH)



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

ENV = env_vars.get('ENV', 'Local')
SECRET_KEY = env_vars.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_vars.get('DEBUG') == 'True'

ALLOWED_HOSTS = env_vars.get('ALLOWED_HOSTS').split(',') if env_vars.get('ALLOWED_HOSTS') else []

# AWS Credentials
AWS_ACCESS_KEY_ID = env_vars.get('AWS_ACCESS_KEY')
AWS_SECRET_ACCESS_KEY = env_vars.get('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = env_vars.get('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = env_vars.get('AWS_S3_REGION_NAME')
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'


# Application definition
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',

    # Custom Apps
    'administration',
    'dashboard'
]

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'
MESSAGE_LEVEL = 20

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Saryupari_Brahmin_Project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'dashboard.context_processors.payment_status',  # Add payment status to all templates
            ],
        },
    },
]

WSGI_APPLICATION = 'Saryupari_Brahmin_Project.wsgi.application'
AUTH_USER_MODEL = 'administration.CustomUser'
LOGIN_URL = '/'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Jazzmin Settings for Admin Panel
JAZZMIN_SETTINGS = {
    "site_title": "Saryu Pariwar Admin Panel",
    "site_header": "Saryu Pariwar Admin",
    "site_brand": "Saryu Pariwar Admin",
    "site_logo": "images/saryu-parivaar-logo.png",
    "custom_css": "css/custom_admin.css",
    "navigation_expanded": True
}


# SECURE_BROWSER_XSS_FILTER = True
# SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_SSL_REDIRECT = env_vars.get('SECURE_SSL_REDIRECT') == 'True'
SESSION_COOKIE_SECURE = env_vars.get('SESSION_COOKIE_SECURE') == 'True'
CSRF_COOKIE_SECURE = env_vars.get('CSRF_COOKIE_SECURE') == 'True'
X_FRAME_OPTIONS = 'DENY'

# CSRF Settings
# Only set cookie domain if explicitly provided (not empty string)
csrf_cookie_domain = env_vars.get('CSRF_COOKIE_DOMAIN', '').strip()
CSRF_COOKIE_DOMAIN = csrf_cookie_domain if csrf_cookie_domain else None

session_cookie_domain = env_vars.get('SESSION_COOKIE_DOMAIN', '').strip()
SESSION_COOKIE_DOMAIN = session_cookie_domain if session_cookie_domain else None

# CSRF Trusted Origins - parse from env or use default
csrf_origins_str = env_vars.get('CSRF_TRUSTED_ORIGINS', '')
if csrf_origins_str:
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_origins_str.split(',') if origin.strip()]
else:
    # Default trusted origins
    CSRF_TRUSTED_ORIGINS = [
        'http://127.0.0.1:8000',
        'http://localhost:8000',
        'https://saryuparivar.com',
        'https://www.saryuparivar.com',
        'http://saryuparivar.com',
        'http://www.saryuparivar.com',
    ]

# If using HTTPS behind a proxy (like Nginx)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR.joinpath('staticfiles')
STATICFILES_DIRS = [
    BASE_DIR.joinpath('static'),
]

# Media files configuration
# For development: Use local storage for uploads, S3 for reading existing images
# For production: Use S3 for both uploads and reads
# Images are served through Django views using boto3 (not direct S3 URLs)

# Check if we're in development (local) or production
USE_LOCAL_STORAGE_FOR_UPLOADS = ENV == 'Local'  # Use local storage in development

# Always set up local storage as fallback
MEDIA_ROOT = BASE_DIR.joinpath('media')
MEDIA_URL = '/media/'
os.makedirs(MEDIA_ROOT, exist_ok=True)

if AWS_STORAGE_BUCKET_NAME and AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY:
    if USE_LOCAL_STORAGE_FOR_UPLOADS:
        # Development: Use local storage for new uploads
        # S3 is used only for reading existing images (via boto3 views)
        DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
        print("📁 Using LOCAL storage for file uploads (development mode)")
    else:
        # Production: Try S3, but MediaStorage will fallback to local if credentials invalid
        DEFAULT_FILE_STORAGE = 'Saryupari_Brahmin_Project.storages.MediaStorage'
        print("☁️  Attempting to use S3 storage (will fallback to local if credentials invalid)")
    
    # S3 Settings (for reading existing images)
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    # ACLs are disabled on this bucket - use bucket policy for public access instead
    AWS_DEFAULT_ACL = None  # Don't set ACLs (bucket doesn't support them)
    AWS_QUERYSTRING_AUTH = False  # Don't add query string authentication
else:
    # Fallback to local if S3 credentials not available
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
    print("⚠️  S3 credentials not found, using LOCAL storage")

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration
EMAIL_BACKEND = env_vars.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = env_vars.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(env_vars.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = env_vars.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_USE_SSL = env_vars.get('EMAIL_USE_SSL', 'False') == 'True'
EMAIL_HOST_USER = env_vars.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = env_vars.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = env_vars.get('DEFAULT_FROM_EMAIL', 'noreply@saryuparivar.com')
SERVER_EMAIL = DEFAULT_FROM_EMAIL
