# Generated by Django 5.0 on 2025-01-09 18:50

import dashboard.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarriageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('head_of_the_family_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('height_feet', models.PositiveIntegerField(blank=True, null=True)),
                ('height_inches', models.PositiveIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('education', models.CharField(max_length=500)),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField(blank=True, null=True)),
                ('time_of_birth', models.TimeField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('gotra', models.CharField(blank=True, max_length=100, null=True)),
                ('native_village', models.CharField(blank=True, max_length=500, null=True)),
                ('district', models.CharField(max_length=500)),
                ('tehsil', models.CharField(blank=True, max_length=500, null=True)),
                ('current_address', models.TextField()),
                ('phone_number', models.BigIntegerField(unique=True, validators=[dashboard.models.validate_phone_number])),
                ('business_address', models.TextField(blank=True, null=True)),
                ('business_phone_number', models.BigIntegerField(blank=True, null=True, validators=[dashboard.models.validate_phone_number])),
                ('marriage_profile_pic', models.ImageField(upload_to='marriage_profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marriage Profile',
                'verbose_name_plural': 'Marriage Profiles',
            },
        ),
    ]
