# Generated by Django 5.0 on 2025-01-11 08:13

import dashboard.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_name', models.CharField(max_length=500)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('height', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('education', models.CharField(max_length=500)),
                ('occupation', models.CharField(max_length=500)),
                ('annual_income', models.CharField(blank=True, max_length=100, null=True)),
                ('father_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField(blank=True, null=True)),
                ('time_of_birth', models.TimeField(blank=True, null=True)),
                ('is_mangalik', models.BooleanField(default=False)),
                ('gotra', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_place', models.CharField(max_length=500)),
                ('father_or_guardian_occupation', models.CharField(max_length=500)),
                ('current_address', models.TextField()),
                ('pincode', models.CharField(max_length=6)),
                ('phone_number', models.BigIntegerField(unique=True, validators=[dashboard.models.validate_phone_number])),
                ('whatsapp_phone_number', models.BigIntegerField(blank=True, null=True, unique=True, validators=[dashboard.models.validate_phone_number])),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('partner_preference', models.CharField(blank=True, max_length=500, null=True)),
                ('if_candidate_is_widow_widower_divorced_or_disabled', models.CharField(blank=True, max_length=500, null=True)),
                ('marriage_profile_pic', models.ImageField(upload_to='marriage_profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marriage Profile',
                'verbose_name_plural': 'Marriage Profiles',
            },
        ),
    ]
