# Generated by Django 5.0 on 2025-01-11 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_candidateprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='is_mangalik',
            new_name='is_manglik',
        ),
    ]
