# Generated by Django 5.0 on 2025-01-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_is_mangalik_candidateprofile_is_manglik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
