# Generated by Django 5.0 on 2025-01-11 09:22

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_candidateprofile_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[dashboard.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='whatsapp_phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[dashboard.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='marriageprofile',
            name='business_phone_number',
            field=models.BigIntegerField(blank=True, max_length=10, null=True, validators=[dashboard.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='marriageprofile',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[dashboard.models.validate_phone_number]),
        ),
    ]
