# Generated by Django 5.0 on 2025-01-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_candidateprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
