# Generated by Django 5.0 on 2025-01-11 09:40

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_candidateprofile_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marriageprofile',
            name='business_phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[dashboard.models.validate_phone_number]),
        ),
    ]
