# Generated by Django 5.0 on 2025-01-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_marriageprofile_business_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='whatsapp_phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='marriageprofile',
            name='business_phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='marriageprofile',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
