# Generated by Django 5.0 on 2025-01-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_candidateprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='city',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
