# Generated by Django 4.2.16 on 2025-11-27 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0009_candidateprofile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='is_shared',
            field=models.BooleanField(default=True, help_text='Share this profile in matrimonial listings'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='relationship_to_user',
            field=models.CharField(blank=True, help_text='Relationship to profile creator (e.g., Son, Daughter, Self, Brother, Sister, etc.)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='user',
            field=models.ForeignKey(help_text='User who created this profile (can create multiple profiles for family members)', on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='whatsapp_phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
