# Generated by Django 4.2.16 on 2025-11-27 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0010_candidateprofile_is_shared_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortlistedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_by', to='dashboard.candidateprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shortlisted Profile',
                'verbose_name_plural': 'Shortlisted Profiles',
                'unique_together': {('user', 'profile')},
            },
        ),
    ]
